export type EmissionScope = "Scope 1" | "Scope 2" | "Scope 3";

export type EmissionFactorDefinition = {
  id: string;
  scope: EmissionScope;
  category: string;
  source: string;
  value: number;
  activityUnit: string;
  factorUnit: string;
  year: string;
  authority: string;
  active: boolean;
  factorType: "공식계수" | "공급자계수" | "참고계수";
  method: string;
  reference: string;
  referenceUrl: string;
  notes: string;
};

export const DEFAULT_EMISSION_FACTORS: EmissionFactorDefinition[] = [
  {
    id: "EF-S1-LNG-2022",
    scope: "Scope 1",
    category: "고정연소",
    source: "도시가스(LNG)",
    value: 2.176,
    activityUnit: "Nm³",
    factorUnit: "kgCO₂e/Nm³",
    year: "2022",
    authority: "환경부·기존 SEMS 기준",
    active: true,
    factorType: "공식계수",
    method: "사용량 × 연료별 순발열량 × 탄소배출계수 × 산화율 × 44/12",
    reference: "배출권거래제 배출량 보고·인증 지침 및 국가 온실가스 배출계수",
    referenceUrl: "https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulId=2075025",
    notes: "기존 SEMS 운영계수 복원값입니다. 청구서 단위와 표준상태(Nm³) 여부를 확인하세요.",
  },
  {
    id: "EF-S1-DIESEL-2022",
    scope: "Scope 1",
    category: "이동연소",
    source: "경유",
    value: 2.582,
    activityUnit: "L",
    factorUnit: "kgCO₂e/L",
    year: "2022",
    authority: "환경부·기존 SEMS 기준",
    active: true,
    factorType: "공식계수",
    method: "연료 사용량 × 연료별 CO₂e 배출계수",
    reference: "배출권거래제 배출량 보고·인증 지침 및 국가 온실가스 배출계수",
    referenceUrl: "https://tips.energy.or.kr/carbon/Ggas_tatistics03.do",
    notes: "회사가 운영통제하는 차량·장비의 연료만 Scope 1로 분류합니다.",
  },
  {
    id: "EF-S1-GASOLINE-2022",
    scope: "Scope 1",
    category: "이동연소",
    source: "휘발유",
    value: 2.179,
    activityUnit: "L",
    factorUnit: "kgCO₂e/L",
    year: "2022",
    authority: "환경부·기존 SEMS 기준",
    active: true,
    factorType: "공식계수",
    method: "연료 사용량 × 연료별 CO₂e 배출계수",
    reference: "배출권거래제 배출량 보고·인증 지침 및 국가 온실가스 배출계수",
    referenceUrl: "https://tips.energy.or.kr/carbon/Ggas_tatistics03.do",
    notes: "차량 소유 여부보다 운영통제 여부를 우선 확인합니다.",
  },
  {
    id: "EF-S1-KEROSENE-2022",
    scope: "Scope 1",
    category: "고정연소",
    source: "등유",
    value: 2.491,
    activityUnit: "L",
    factorUnit: "kgCO₂/L",
    year: "2022",
    authority: "한국에너지공단",
    active: true,
    factorType: "공식계수",
    method: "34.1 MJ/L × 19.926 tC/TJ × 44/12",
    reference: "국가 온실가스 배출계수(순발열량·탄소배출계수)",
    referenceUrl: "https://tips.energy.or.kr/carbon/Ggas_tatistics03.do",
    notes: "CH₄·N₂O 포함 여부와 산화율 적용 기준은 조직의 산정방침에 맞춰 일관되게 관리하세요.",
  },
  {
    id: "EF-S1-LPG-2022",
    scope: "Scope 1",
    category: "고정·이동연소",
    source: "LPG(프로판)",
    value: 2.987,
    activityUnit: "kg",
    factorUnit: "kgCO₂/kg",
    year: "2022",
    authority: "한국에너지공단",
    active: true,
    factorType: "공식계수",
    method: "46.2 MJ/kg × 17.630 tC/TJ × 44/12",
    reference: "국가 온실가스 배출계수(순발열량·탄소배출계수)",
    referenceUrl: "https://tips.energy.or.kr/carbon/Ggas_tatistics03.do",
    notes: "구매자료가 L 단위이면 밀도 등 적정 환산근거를 별도로 보관하세요.",
  },
  {
    id: "EF-S1-ACETYLENE",
    scope: "Scope 1",
    category: "공정배출",
    source: "아세틸렌",
    value: 3.385,
    activityUnit: "kg",
    factorUnit: "kgCO₂/kg",
    year: "상시",
    authority: "화학양론",
    active: true,
    factorType: "공식계수",
    method: "C₂H₂ 완전연소 반응식 기준: 사용량 × 88/26",
    reference: "아세틸렌 완전연소 화학양론",
    referenceUrl: "https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol2.html",
    notes: "실제 사용 공정과 회수·잔량 여부를 확인하고 구매량 또는 실사용량 기준을 명시하세요.",
  },
  {
    id: "EF-S1-WELDING-CO2",
    scope: "Scope 1",
    category: "공정배출",
    source: "용접용 CO₂",
    value: 1,
    activityUnit: "kg",
    factorUnit: "kgCO₂e/kg",
    year: "상시",
    authority: "질량수지",
    active: true,
    factorType: "공식계수",
    method: "외부에서 구매한 순수 CO₂ 사용량 × 1",
    reference: "GHG Protocol Corporate Standard·질량수지",
    referenceUrl: "https://ghgprotocol.org/corporate-standard",
    notes: "용접 과정에서 대기로 방출되는 구매 CO₂는 직접배출(Scope 1)로 관리합니다.",
  },
  {
    id: "EF-S1-R410A-AR4",
    scope: "Scope 1",
    category: "탈루배출",
    source: "냉매 R410A",
    value: 2088,
    activityUnit: "kg",
    factorUnit: "kgCO₂e/kg",
    year: "AR4",
    authority: "IPCC",
    active: true,
    factorType: "공식계수",
    method: "냉매 충전·보충량 × 적용 GWP",
    reference: "IPCC AR4 GWP",
    referenceUrl: "https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol3.html",
    notes: "보고제도에 따라 적용 GWP 버전이 달라질 수 있으므로 보고연도 기준을 확인하세요.",
  },
  {
    id: "EF-S2-ELECTRICITY-SEMS",
    scope: "Scope 2",
    category: "구매전력",
    source: "전력(기존 SEMS)",
    value: 0.45941,
    activityUnit: "kWh",
    factorUnit: "kgCO₂e/kWh",
    year: "기존 기준",
    authority: "기존 SEMS 운영계수",
    active: true,
    factorType: "공식계수",
    method: "구매전력 사용량 × 적용 전력 배출계수",
    reference: "기존 SEMS 월별 Scope 2 산정기준",
    referenceUrl: "https://tips.energy.or.kr/carbon/Ggas_tatistics03.do",
    notes: "기존 실적 재현용 계수입니다. 신규 보고에는 해당 보고제도의 적용연도 계수를 선택하세요.",
  },
  {
    id: "EF-S2-ELECTRICITY-2023",
    scope: "Scope 2",
    category: "구매전력",
    source: "전력(2023 소비단)",
    value: 0.4173,
    activityUnit: "kWh",
    factorUnit: "kgCO₂e/kWh",
    year: "2023",
    authority: "한국에너지공단·온실가스종합정보센터",
    active: true,
    factorType: "공식계수",
    method: "구매전력 사용량 × 0.4173 kgCO₂e/kWh",
    reference: "국가 전력 배출계수, 2023년 소비단 CO₂eq",
    referenceUrl: "https://tips.energy.or.kr/carbon/Ggas_tatistics03.do",
    notes: "위치기반 산정용입니다. 보고연도와 공시 요구사항에 맞는 계수를 고정해 사용하세요.",
  },
  {
    id: "EF-S2-ELECTRICITY-AVG-2123",
    scope: "Scope 2",
    category: "구매전력",
    source: "전력(2021~2023 평균 소비단)",
    value: 0.433,
    activityUnit: "kWh",
    factorUnit: "kgCO₂e/kWh",
    year: "2021~2023",
    authority: "한국에너지공단·온실가스종합정보센터",
    active: true,
    factorType: "공식계수",
    method: "구매전력 사용량 × 3개년 평균 소비단 계수",
    reference: "국가 전력 배출계수, 2021~2023 평균 소비단 CO₂eq",
    referenceUrl: "https://tips.energy.or.kr/carbon/Ggas_tatistics03.do",
    notes: "단년도 계수와 혼용하지 말고 산정방침에 선택 근거를 남기세요.",
  },
  {
    id: "EF-S2-STEAM-SUPPLIER",
    scope: "Scope 2",
    category: "구매열",
    source: "스팀",
    value: 0.221,
    activityUnit: "kg",
    factorUnit: "kgCO₂e/kg",
    year: "공급자 기준",
    authority: "기존 SEMS·공급자 확인 필요",
    active: true,
    factorType: "공급자계수",
    method: "구매 스팀량 × 공급자 배출계수",
    reference: "열 공급자 명세서 또는 검증된 배출계수",
    referenceUrl: "",
    notes: "열원·압력·환산단위가 공급자별로 다르므로 공급자 계수를 우선 사용하고 증빙을 연결하세요.",
  },
  {
    id: "EF-S3-CAT1-STEEL",
    scope: "Scope 3",
    category: "Cat.1 구매한 제품 및 서비스",
    source: "철강재",
    value: 2.1,
    activityUnit: "kg",
    factorUnit: "kgCO₂e/kg",
    year: "참고",
    authority: "기존 SEMS 참고계수",
    active: true,
    factorType: "참고계수",
    method: "구매 중량 × 품목별 배출계수",
    reference: "공급자 PCF·EPD 우선, 미확보 시 검증된 LCA DB",
    referenceUrl: "https://ghgprotocol.org/scope-3-calculation-guidance-2",
    notes: "철강 종류·재생원료 함량·공정에 따라 차이가 큽니다. 공급자별 PCF 확보 시 교체하세요.",
  },
  {
    id: "EF-S3-CAT4-LOGISTICS",
    scope: "Scope 3",
    category: "Cat.4 업스트림 운송 및 유통",
    source: "구매 물류",
    value: 0.109,
    activityUnit: "ton-km",
    factorUnit: "kgCO₂e/ton-km",
    year: "참고",
    authority: "기존 SEMS 참고계수",
    active: true,
    factorType: "참고계수",
    method: "운송중량(t) × 거리(km) × 운송수단별 계수",
    reference: "GHG Protocol Scope 3 Calculation Guidance",
    referenceUrl: "https://ghgprotocol.org/scope-3-calculation-guidance-2",
    notes: "차량과 기사를 공급자가 통제하고 운임만 지불한 경우 Cat.4로 분류합니다.",
  },
  {
    id: "EF-S3-CAT5-WASTE",
    scope: "Scope 3",
    category: "Cat.5 사업장 발생 폐기물",
    source: "일반폐기물",
    value: 0.467,
    activityUnit: "kg",
    factorUnit: "kgCO₂e/kg",
    year: "참고",
    authority: "기존 SEMS 참고계수",
    active: true,
    factorType: "참고계수",
    method: "폐기물 종류별 중량 × 처리방법별 배출계수",
    reference: "GHG Protocol Scope 3 Calculation Guidance",
    referenceUrl: "https://ghgprotocol.org/scope-3-calculation-guidance-2",
    notes: "매립·소각·재활용 등 처리방법별 계수를 구분해야 하며 올바로 자료와 연계하세요.",
  },
  {
    id: "EF-S3-CAT6-TRAVEL",
    scope: "Scope 3",
    category: "Cat.6 출장",
    source: "승용차 출장",
    value: 0.171,
    activityUnit: "km",
    factorUnit: "kgCO₂e/km",
    year: "참고",
    authority: "기존 SEMS 참고계수",
    active: true,
    factorType: "참고계수",
    method: "이동거리 × 교통수단별 배출계수",
    reference: "GHG Protocol Scope 3 Calculation Guidance",
    referenceUrl: "https://ghgprotocol.org/scope-3-calculation-guidance-2",
    notes: "항공·철도·택시·자가용을 구분하고 가능하면 실제 운송수단별 계수를 사용하세요.",
  },
  {
    id: "EF-S3-CAT7-COMMUTE",
    scope: "Scope 3",
    category: "Cat.7 임직원 통근",
    source: "임직원 통근",
    value: 0.121,
    activityUnit: "km",
    factorUnit: "kgCO₂e/km",
    year: "참고",
    authority: "기존 SEMS 참고계수",
    active: true,
    factorType: "참고계수",
    method: "인원 × 왕복거리 × 출근일수 × 교통수단별 계수",
    reference: "GHG Protocol Scope 3 Calculation Guidance",
    referenceUrl: "https://ghgprotocol.org/scope-3-calculation-guidance-2",
    notes: "표본 설문 사용 시 응답률·외삽방법·재택근무일을 산정근거에 기록하세요.",
  },
  {
    id: "EF-S3-CAT9-LOGISTICS",
    scope: "Scope 3",
    category: "Cat.9 다운스트림 운송 및 유통",
    source: "판매 물류",
    value: 0.109,
    activityUnit: "ton-km",
    factorUnit: "kgCO₂e/ton-km",
    year: "참고",
    authority: "기존 SEMS 참고계수",
    active: true,
    factorType: "참고계수",
    method: "판매제품 운송중량(t) × 거리(km) × 운송수단별 계수",
    reference: "GHG Protocol Scope 3 Calculation Guidance",
    referenceUrl: "https://ghgprotocol.org/scope-3-calculation-guidance-2",
    notes: "운송비 부담과 운송서비스 구매 주체에 따라 Cat.4 또는 Cat.9 경계를 구분하세요.",
  },
];

export const SCOPE_GUIDANCE = [
  {
    scope: "Scope 1" as const,
    title: "직접배출",
    definition: "회사가 소유하거나 운영통제하는 설비·차량·공정에서 직접 발생하는 배출",
    examples: "LNG·경유·휘발유·LPG·등유 연소, 냉매 누출, 아세틸렌·용접용 CO₂",
    formula: "활동량 × 연료·공정계수 또는 질량수지",
    standard: "GHG Protocol Corporate Standard · 배출권거래제 보고·인증 지침",
    caution: "소유보다 운영통제를 우선 판단하고 고정연소·이동연소·공정·탈루를 구분합니다.",
  },
  {
    scope: "Scope 2" as const,
    title: "구매에너지 간접배출",
    definition: "외부에서 구매해 소비한 전력·열·스팀·냉방 생산 과정에서 발생하는 간접배출",
    examples: "한국전력 구매전력, 외부 공급 스팀·열",
    formula: "구매 에너지 사용량 × 위치기반 또는 시장기반 배출계수",
    standard: "GHG Protocol Scope 2 Guidance · 국가 전력 배출계수",
    caution: "위치기반·시장기반 결과를 구분하고, 연도별 전력계수를 기존 실적에 소급 혼용하지 않습니다.",
  },
  {
    scope: "Scope 3" as const,
    title: "기타 간접배출",
    definition: "회사의 가치사슬에서 발생하지만 Scope 1·2에 포함되지 않는 15개 범주의 배출",
    examples: "Cat.1 구매품, Cat.4 물류, Cat.5 폐기물, Cat.6 출장, Cat.7 통근, Cat.9 판매물류",
    formula: "공급자 실제값 또는 활동량·지출액 × 범주별 계수",
    standard: "GHG Protocol Scope 3 Standard · Scope 3 Calculation Guidance",
    caution: "단일 공통계수는 없습니다. 공급자 PCF·EPD·실제 활동량을 우선하고 추정값에는 출처와 가정을 남깁니다.",
  },
];

export const SCOPE3_CATEGORIES = [
  { code: "Cat.1", name: "구매한 제품 및 서비스", method: "공급자 PCF·EPD 또는 구매량 × 품목별 LCA 계수" },
  { code: "Cat.2", name: "자본재", method: "설비·건물 취득액 또는 중량 × 자본재별 계수" },
  { code: "Cat.3", name: "연료·에너지 관련 활동", method: "연료·전력 사용량 × 업스트림·송배전 계수" },
  { code: "Cat.4", name: "업스트림 운송 및 유통", method: "중량 × 거리 × 운송수단별 계수 또는 운송비 기반" },
  { code: "Cat.5", name: "사업장 발생 폐기물", method: "폐기물 중량 × 종류·처리방법별 계수" },
  { code: "Cat.6", name: "출장", method: "이동거리·숙박일수 × 교통·숙박 계수" },
  { code: "Cat.7", name: "임직원 통근", method: "인원 × 거리 × 출근일수 × 교통수단별 계수" },
  { code: "Cat.8", name: "업스트림 임차자산", method: "임차자산 에너지 사용량 × 에너지원별 계수" },
  { code: "Cat.9", name: "다운스트림 운송 및 유통", method: "판매제품 중량 × 거리 × 운송수단별 계수" },
  { code: "Cat.10", name: "판매제품 가공", method: "판매 중간재 가공량 × 공정별 에너지·배출계수" },
  { code: "Cat.11", name: "판매제품 사용", method: "판매수량 × 수명기간 사용량 × 에너지원별 계수" },
  { code: "Cat.12", name: "판매제품 폐기", method: "판매제품 중량 × 재질·처리방법별 계수" },
  { code: "Cat.13", name: "다운스트림 임대자산", method: "임대자산 에너지 사용량 × 에너지원별 계수" },
  { code: "Cat.14", name: "프랜차이즈", method: "가맹점 에너지·연료 사용량 × 배출계수" },
  { code: "Cat.15", name: "투자", method: "피투자회사 배출량 × 지분율 또는 자산군별 금융배출 방법론" },
];

export function withDefaultEmissionFactors(values: unknown[]) {
  return values.length ? values : DEFAULT_EMISSION_FACTORS.map((factor) => ({ ...factor }));
}

export function mergeDefaultEmissionFactors<T extends { id?: string }>(values: T[]) {
  const ids = new Set(values.map((value) => value.id));
  return [
    ...values,
    ...DEFAULT_EMISSION_FACTORS.filter((factor) => !ids.has(factor.id)).map((factor) => ({ ...factor })),
  ];
}
